### ISSUE TITLE
Multiple instances of an instruction named ... when trying to parse the newest GGST scripts. 

### ISSUE THREAD

**Issue by AregevDev** [super-continent/bbscript#34]
Hi, I was trying to extract scripts for the latest GGST version (300) I used `FModel` and `ggst-bbscript-unpacker` to get the script files.

However I run into an error when running `bbscript.exe`:

```
bbscript.exe parse ggst .\BBS_SOL_300.bbs SOL.bbscript
ERROR: Config contains multiple instances of an instruction named `defaultGravity`
```
When running the command multiple times, it complains about `setLightRedColor` and `faceBrowReset` instructions as well

No idea how to get around this.

**Comment by super-continent** [comment]
Are you using the latest config files? they should be working fine now. Try downloading the from the static_db folder in this repository and replacing the contents of your folder with the current ones

**Comment by AregevDev** [comment]
Thanks I'll give it a shot

**Comment by SilverDash** [comment]
Using latest release and downloading the ron file from the repo, this issue still persists

ERROR: Config contains multiple instances of an instruction named `setLightRedColor`

**Comment by super-continent** [comment]
which config file? there might be some that still have issues

**Comment by super-continent** [comment]
I put out a new release just now that embeds config files. You won't need to download them anymore. Just supply a `--game` argument and it will use the embedded one. Automated testing guarantees that check doesn't fail with all current configs
